server:
  port: 8787
spring:
  application:
    name: ApiGateWay_Eureka
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceA/**
        - id: Microservice2
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceB/**
        - id: Tasks
          uri: http://localhost:8083/
          predicates:
            - Path=/tasks/**
