server:
  servlet:
    encoding:
      - charset=UTF-8
      - force=true
  port: 8080

spring:
  application:
    name: Tasks

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
